### PR TITLE
Batch of Tools, Updates, and Fixes

### LINKED ISSUE #21: The march meetup isn't showing up on the site
I haven't had a chance to look into this yet, but the website doesn't show the march meetup for some reason.

### PR DESCRIPTION
**Pull request by nelsonjchen**
Preview: https://nelsonjchen.github.io/desertpy-pelican/

This should close #21 . There are now two sections: Upcoming and Previous. Upcoming will show that meetup first.

I opted to integrate the About Page into the front page. I can move this back into its own menu item if needed.

Some other light CSS changes were done too. Icons have been added and swapped out sometimes.

Some misc fixes are included too: `CNAME` is not copied if this isn't the main desertpy repo. Also a console script stub was added for easier debugging on Windows. And some more gitignore stuff.

### CODE REVIEW

**Comment by godber** [comment]
I think the "About" should still be on it's own page.  Also, let's remove the "Lightning Talks" link too ... no one has used that for years I bet.  I know I keep forgetting about it.

I like the split between Upcoming and Previously ... but where does that leave actual blog posts?

**Comment by nelsonjchen** [comment]
I was thinking about actual blog posts. 

OK, I'll revert about to it's own page. i think I'll do this:

* <Latest Blog Post (non-meetup tagged)>
* <Upcoming Meetups>
* <Previous Meetups> 

@godber Would that work?

**Comment by nelsonjchen** [comment]
I've removed the lightning talk thing.

I've reverted the About Page thing.

I'm still not sure what to do about the blog post thing. Maybe let's work on that after?

**Comment by nelsonjchen** [comment]
Hmm, maybe the best thing to do is to just:

* Feature the latest blog post and next upcoming meeting
* The rest, excluding the latest blog post and next upcoming meeting.

**Comment by godber** [comment]
Yeah, we can sort it out later. I like how this looks now for sure though .... so I will merge.

**Pull request merged**
